# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62dd6614579cc8ba3ebf9f79a21926614dd98b5e307d0dca70a38e4321669fe5f479fde63536083099d0c456862db96ed3131eaf8a3be1bda8594dbe3b0468aa

test:
  secret_key_base: 3230e62d36846a4bd1952ac0ca9ae556d940b19b61b872c6be4822b2a3d91db380b56554fd85a780f7865400db695f37e7504e8d930605ea964610d078d6e806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
